### ISSUE TITLE
Please Release Version: 0.18.6

### ISSUE THREAD

**Issue by mpellicer** [webjars/ckeditor-autosave#4]
Thank you!

**Comment by jamesward** [comment]
I don't see that release at: https://github.com/w8tcha/CKEditor-AutoSave-Plugin/releases

**Comment by mpellicer** [comment]
You're right, not listed in Github but listed in the webpage:
![image](https://user-images.githubusercontent.com/8653754/127435239-e0e3572e-91e9-4b2b-8c8e-34dcca007358.png)

https://ckeditor.com/cke4/addon/autosave
